[SCANNER]

INTERFACE=default
; NOTE: it's important that this directory is /tmp when the scanner is Dockerized to avoid permission issues
TEMP_PCAP_PATH=/tmp/pcap
ROTATE_EVERY_T_SEC=5

[KAFKA]

IP_CLIENT=172.42.0.11
ADDRESS_SERVER=http://127.0.0.1:9092
TOPIC=network
SASL_MECHANISM=PLAIN
SASL_PLAIN_USERNAME=admin
SASL_PLAIN_PASSWORD=admin
